---
- hosts: all

  roles:
    - role: docker
      tags:
        - docker

    - role: autoheal
      tags:
        - autoheal

    - role: v2ray
      tags:
        - v2ray

    - role: tls-shunt-proxy
      tags:
        - tls-shunt-proxy
        - tls
      when: (tls_shunt_proxy_enabled | default(False))

    - role: ddns
      tags:
        - ddns
        - tls
      when: (tls_shunt_proxy_enabled | default(False))

