---
- name: Uninstall old Docker versions
  apt: 
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  register: result
  until: result is succeeded
  
- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Install some packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - unzip
    state: present
  register: result
  until: result is succeeded

- name: Add Docker's official GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Set up the Docker stable repository
  ansible.builtin.shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 0
  register: result
  until: result is succeeded

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  register: result
  until: result is succeeded

- name: Install Docker Compose
  ansible.builtin.shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
